### ISSUE TITLE
Mac / Linux support

### ISSUE THREAD

**Issue by jackmott** [fsprojects/SIMDArray#11]
Just tried this on linux, and while it builds and runs, the SIMD doesn't look like it is actually happening. I assumed we would need to make this a .net core build for that to work?

**Comment by jackmott** [comment]
So there is a MONO SIMD library, we could probably recreate some of these functions with it, and use some #ifdefs so that it will build and work in either environment. Anyone have experience with mono SIMD?

**Comment by gsomix** [comment]
May be useful.

http://www.mono-project.com/news/2016/12/20/system-numeric-vectors/

**Comment by jackmott** [comment]
i saw that, will test it soon!

**Comment by jackmott** [comment]
I can test out the new Mono runtime soon to see if I can get this working there. I could use some help setting up the project so it will build and be usable under .NET core though. I have no familiarity with that process yet.

**Comment by jackmott** [comment]
While things function on Mono, it doesn't look like the SIMD code is actually being accelerated at least as of Mono 4.9.0 which is the newest package you can download. I will have to build Mono from source to try the new SIMD stuff.  Maybe tonight!

**Comment by jackmott** [comment]
Just tested with mono built from the master branch, still no speedup. Not sure if there are some special incantations needed to enable System.Numerics SIMD support.

**Comment by gsomix** [comment]
http://www.mono-project.com/docs/about-mono/releases/5.0.0/#simd-acceleration-support

**Comment by jackmott** [comment]
Yes I'm very excited for 5.0!

**Comment by gsomix** [comment]
Any updates on it?

**Comment by jackmott** [comment]
@gsomix  Mono 5 is out, and it should work, give it a try.  As well the code should work in .net core.
