### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by jackmott** [fsprojects/SIMDArray#14]
SIMDArray functions that need tests
- [x] `average`  
- [x] `averageBy`  
- [x] `create` 
- [x] `clear` 
- [x] `contains`  
- [x] `compareWith`  
- [x] `exists`  
- [x] `exists2`  
- [x] `filter`  (not SIMD enhanced, but much faster in certain cases)
- [x] `find`  
- [x] `findBack`  
- [x] `findIndex`  
- [x] `findIndexBack`  
- [x] `fold`  
- [x] `fold2`  
- [x] `foldBack`  
- [x] `foldBack2`  
- [x] `forall`  
- [x] `forall2`  
- [x] `init`  
- [x] `iter`  
- [x] `iter2`  
- [x] `iteri`  
- [x] `iteri2`  
- [x] `map`  
- [x] `map2`  
- [x] `map3`  
- [x] `mapi`  
- [x] `mapi2`  
- [x] `max`  
- [x] `maxBy`  
- [x] `min`  
- [x] `minBy`  
- [x] `pick`  
- [x] `reduce`  
- [x] `reduceBack`  
- [x] `replicate`  
- [x] `skipWhile`  
- [x] `sum`  
- [x] `sumBy`  
- [x] `takeWhile`  
- [x] `tryFind`  
- [x] `tryFindBack`  
- [x] `tryFindIndex`  
- [x] `tryFindIndexBack`  
- [x] `tryPick`  
- [x] `where`   - see filter, as these just alias those
- [x] `mapFold`  
- [x] `mapFoldBack`  
- [x] `fill`

**Comment by delneg** [comment]
Closed via #27
