### ISSUE TITLE
fsprojects?

### ISSUE THREAD

**Issue by dsyme** [fsprojects/SIMDArray#15]
Hi Jack

Awesome project! Am watching it now. 

Let me know if you'd like to move this to "fsprojects".  Moving to a community organization can sometimes be useful to bring in more contributors especially on orthogonal concerns like Mono support etc.  You'd maintain full admin rights of course - by default Sergey Tihon would also be added

No obligation whatsoever - just wanted to ask.

Best 
Don

**Comment by dsyme** [comment]
Also maybe we should list this on http://fsharp.org/community/projects

**Comment by jackmott** [comment]
Hello Don,

Yes I would be happy to get this moved into fsprojects.  I could use some help with the final polish, .net core support and so on.

**Comment by dsyme** [comment]
@jackmott Please either give me admin access, or I think you may be able to do the transfer yourself.  Or work with @forki who will help you do the transfer :)

Thanks!
don

**Comment by forki** [comment]
Yeah I'm happy to help. But would need admin access as well ;-)

**Comment by forki** [comment]
ok will start the process.

**Comment by forki** [comment]
@jackmott you made me colleborator, but I need admin access

**Comment by jackmott** [comment]
yes, I'm poking around looking at how to do that. Any tips?

**Comment by jackmott** [comment]
looks like I need to move it to an org first, one moment

**Comment by jackmott** [comment]
ok you should both be admin now, I believe.

**Comment by forki** [comment]
done
