### ISSUE TITLE
Dot product

### ISSUE THREAD

**Issue by buybackoff** [fsprojects/SIMDArray#17]
Hi,

I was pretty sure that dot product was there since it is in [Vector API](https://msdn.microsoft.com/en-us/library/dn889236(v=vs.111).aspx), but it is not yet implemented. Could do it later myself (but without  ETA, just needed a quick SIMD fix inside a tight loop and will live with a `for` loop for now)...

**Comment by jackmott** [comment]
dot product is added thanks to @marklam
