### ISSUE TITLE
minBy and maxBy don't match Array methods

### ISSUE THREAD

**Issue by marklam** [fsprojects/SIMDArray#21]
### Description

The minBy and maxBy functions return the minimum/maximum value of the projection, not the input value. 
The signature shows that the return value is the value from the function, not the value from the array.

### Repro steps

```[<Test>]                  
let ``SIMD.maxBy`` () =
    let xs = [| -5..-1 |]
    Assert.AreEqual(-5, xs |> Array.maxBy (fun x -> -x))
    Assert.AreEqual(-5, xs |> Array.SIMD.maxBy (fun v -> -v) (fun x -> -x))

[<Test>]                  
let ``SIMD.minBy`` () =
    let xs = [| -5..-1 |]
    Assert.AreEqual(-1, xs |> Array.minBy (fun x -> -x))
    Assert.AreEqual(-1, xs |> Array.SIMD.minBy (fun v -> -v) (fun x -> -x))
```

### Expected behavior

Array.SIMD.minBy should match Array.minBy (and similarly for maxBy)

### Actual behavior

The values returned are the values from the selector functions.

**Comment by jackmott** [comment]
good catch. I can work on a fix unless you already have one incoming?

**Comment by marklam** [comment]
No, I started but it wasn't obvious to me how to track which element of the two input vectors corresponded to the element selected by Vector.Max.
So then I made like Brave Sir Robin, and gave up :-(

**Comment by jackmott** [comment]
Yes I am thinking hard on the most efficient way to do that too!

**Comment by jackmott** [comment]
heh, I have discovered SIMD min treats nan differently than the < operator does.

**Comment by marklam** [comment]
I've poked about a bit and done a bit of searching, and you can tell if a Vector contains a NaN by using
``Vector.EqualsAll(v, v)`` because the only element in a vector that isn't equal to itself is ``NaN``.
If any vector returned by the mapping contains a NaN, then the rest can be skipped.
