### ISSUE TITLE
1+Gb folder size after build!?

### ISSUE THREAD

**Issue by buybackoff** [fsprojects/SIMDArray#6]
It is not even a .NET Core project, but for some reason it downloads everything that is already on any machine with .NET 4.5. It is about 1.4 Mb per line of code in SIMDArray.fs (719 lines) :smile:

**Comment by jackmott** [comment]
@cloudRoutine have we got stuff in paket dependencies we don't  need? How can we check?

@buybackoff A lot of the packages are for testing and benchmarking, the SIMDArray lib itsef only uses System.Numerics.Vectors (and its depedencies)

**Comment by cloudRoutine** [comment]
One of the dependencies is pulling in a bunch of netcore stuff 

![](http://i.imgur.com/RR8B9Al.png)

**Comment by jackmott** [comment]
I think it may be BenchmarkingDotNet

**Comment by jackmott** [comment]
Also, we will want to be a .NET core project eventually, if this is going to work on Mac/Linux

**Comment by jackmott** [comment]
Down to ~655 megs now

**Comment by jackmott** [comment]
Going to close this for now, if someone thinks it is a major issue we can look at having build ignore the benchmarking suite by default or something.
