### ISSUE TITLE
Normalization With F# Collections API

### ISSUE THREAD

**Issue by cloudRoutine** [fsprojects/SIMDArray#7]
Here's a list of the collections functions as of F# 4.0
- [x] `average`  
- [x] `averageBy`  
- [x] `contains`  
- [x] `compareWith`  
- [x] `exists`  
- [x] `exists2`  
- [x] `filter`  (not SIMD enhanced, but much faster in certain cases)
- [x] `find`  
- [x] `findBack`  
- [x] `findIndex`  
- [x] `findIndexBack`  
- [x] `fold`  
- [x] `fold2`  
- [x] `foldBack`  
- [x] `foldBack2`  
- [x] `forall`  
- [x] `forall2`  
- [x] `init`  
- [x] `iter`  
- [x] `iter2`  
- [x] `iteri`  
- [x] `iteri2`  
- [x] `map`  
- [x] `map2`  
- [x] `map3`  
- [x] `mapi`  
- [x] `mapi2`  
- [x] `max`  
- [x] `maxBy`  
- [x] `min`  
- [x] `minBy`  
- [x] `pick`  
- [x] `reduce`  
- [x] `reduceBack`  
- [x] `replicate`  
- [x] `skipWhile`  
- [x] `sum`  
- [x] `sumBy`  
- [x] `takeWhile`  
- [x] `tryFind`  
- [x] `tryFindBack`  
- [x] `tryFindIndex`  
- [x] `tryFindIndexBack`  
- [x] `tryPick`  
- [x] `where`   - see filter, as these just alias those
- [x] `mapFold`  
- [x] `mapFoldBack`  
### Mutation-related
- [x] `create`  
- [x] `fill`  
### Probably do not make sense to implement
-  `rev`   (until System.Numerics exposes shuffle operations)
-  `sort`    (like rev, sort needs exposed shuffle operations)  
-  `sortBy`  
-  `sortWith`  
-  `sortDescending`  
-  `sortByDescending`  
-  `head`  
-  `isEmpty` 
-  `last`  
-  `length`  
-  `tryHead`  
-  `tryLast`  
-  `empty`  
-  `item`  
-  `get`  
-  `set`  
-  `singleton`  
-  `zeroCreate`  (simdCreate has to call this first anyway so can't be faster..I think)
-  `tail`  obvious SIMD version tested slower
-  `sub`   same as tail, both call external C code to do fast copy
-  `blit`    same as tail
-  `copy`    similar to tail, can't speed it up
-  `skip`        just calls sub
-  `chunkBySize`   just iterates over sub, which we can't speed up
-  `choose`  
-  `collect`  
- `countBy`    not sure this one makes sense to bother with, but might be possible
- `distinct`  
- `distinctBy`  
- `splitInto`  
- `exactlyOne`  
- `except`  
- `groupBy`  
- `indexed`  
- `pairwise`  
- `permute`  
- `tryItem`  
- `scan`  
- `scanBack`  
- `take`  
- `truncate`  
- `unfold`  
- `windowed`  
- `zip`  
- `zip3`  
- `partition`  
- `splitAt`  
- `unzip`  
- `unzip3`  
- `sortInPlace`  
- `sortInPlaceBy`  
- `sortInPlaceWith`  
- `ofList`  
- `ofArray`  
- `ofSeq`  
- `toList`  
- `toArray`  
- `toSeq`

**Comment by jackmott** [comment]
Updated with a partial list of ones that probably do not make sense to implement. Probably there are more. I wonder if sort can be sped up??

**Comment by jackmott** [comment]
feature complete!
